# Variable for site.*
title: My Website
author: Someone
github: https://github.com/AdrianMP1
description: Personal Website

sass:
  sass_dir: _sass
  style: compressed

collections:
  projects:
    output: true
